name: AMD Gaming Giveaway Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  check-amd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run AMD notifier
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ROLE_PING: ${{ secrets.ROLE_PING }}
        run: python amd_gaming.py

      - name: Save state file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add amd_state.json

          git commit -m "Update AMD giveaway state" || echo "No changes"

          git pull --rebase
          git push
